In [15]:
htlif = {
    'GT':[0.00,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00],
'Mean':[0.13,0.18,0.24,0.34,0.43,0.52,0.60,0.69,0.78,0.87,0.89],
'Median':[0.11,0.16,0.22,0.33,0.42,0.51,0.58,0.68,0.78,0.88,0.90],
'Mode':[0.09,0.14,0.17,0.26,0.44,0.52,0.57,0.61,0.76,0.88,0.90],
'WgtSum':[0.13,0.18,0.24,0.32,0.40,0.49,0.56,0.66,0.76,0.88,0.91],
'WgtProd':[0.13,0.18,0.24,0.32,0.40,0.48,0.56,0.65,0.75,0.87,0.90],
}
biosr = {
    'GT':[0.00,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00],
'Mean':[0.13,0.15,0.21,0.31,0.43,0.54,0.64,0.72,0.77,0.80,0.80],
'Median':[0.12,0.14,0.20,0.28,0.41,0.53,0.64,0.72,0.78,0.79,0.80],
'Mode':[0.11,0.10,0.13,0.27,0.35,0.66,0.61,0.74,0.79,0.78,0.78],
'WgtSum':[0.14,0.16,0.20,0.29,0.42,0.54,0.63,0.71,0.77,0.79,0.80],
'WgtProd':[0.15,0.16,0.20,0.27,0.40,0.51,0.61,0.69,0.76,0.80,0.81],
}
htt24 = {
    'GT':[0.00,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00],
'Mean':[0.13,0.14,0.25,0.35,0.45,0.53,0.61,0.69,0.78,0.87,0.92],
'Median':[0.10,0.12,0.23,0.35,0.45,0.54,0.62,0.70,0.80,0.89,0.96],
'Mode':[0.09,0.10,0.22,0.35,0.46,0.54,0.64,0.71,0.79,0.87,0.96],
'WgtSum':[0.11,0.12,0.22,0.34,0.45,0.53,0.61,0.69,0.78,0.86,0.93],
'WgtProd':[0.11,0.12,0.24,0.36,0.46,0.55,0.63,0.71,0.80,0.87,0.92],
}

In [16]:
import pandas as pd
biosr_df = pd.DataFrame(biosr)
htlif_df = pd.DataFrame(htlif)
htt24_df = pd.DataFrame(htt24)

In [17]:
print(htlif_df.to_latex(float_format="%.2f", index_names=False))

\begin{tabular}{lrrrrrr}
\toprule
 & GT & Mean & Median & Mode & WgtSum & WgtProd \\
\midrule
0 & 0.00 & 0.13 & 0.11 & 0.09 & 0.13 & 0.13 \\
1 & 0.10 & 0.18 & 0.16 & 0.14 & 0.18 & 0.18 \\
2 & 0.20 & 0.24 & 0.22 & 0.17 & 0.24 & 0.24 \\
3 & 0.30 & 0.34 & 0.33 & 0.26 & 0.32 & 0.32 \\
4 & 0.40 & 0.43 & 0.42 & 0.44 & 0.40 & 0.40 \\
5 & 0.50 & 0.52 & 0.51 & 0.52 & 0.49 & 0.48 \\
6 & 0.60 & 0.60 & 0.58 & 0.57 & 0.56 & 0.56 \\
7 & 0.70 & 0.69 & 0.68 & 0.61 & 0.66 & 0.65 \\
8 & 0.80 & 0.78 & 0.78 & 0.76 & 0.76 & 0.75 \\
9 & 0.90 & 0.87 & 0.88 & 0.88 & 0.88 & 0.87 \\
10 & 1.00 & 0.89 & 0.90 & 0.90 & 0.91 & 0.90 \\
\bottomrule
\end{tabular}

In [10]:
biosr_df

     GT  Mean  Median  Mode  WeightedBySum  WeightedByProduct
0   0.0  0.13    0.12  0.11           0.14               0.15
1   0.1  0.15    0.14  0.10           0.16               0.16
2   0.2  0.21    0.20  0.13           0.20               0.20
3   0.3  0.31    0.28  0.27           0.29               0.27
4   0.4  0.43    0.41  0.35           0.42               0.40
5   0.5  0.54    0.53  0.66           0.54               0.51
6   0.6  0.64    0.64  0.61           0.63               0.61
7   0.7  0.72    0.72  0.74           0.71               0.69
8   0.8  0.77    0.78  0.79           0.77               0.76
9   0.9  0.80    0.79  0.78           0.79               0.80
10  1.0  0.80    0.80  0.78           0.80               0.81